image:
  - Visual Studio 2022
  - Ubuntu
install:
  - cmd: dotnet restore
  - sh: sudo apt-get update && sudo apt-get install -y libfontconfig1
build:
  verbosity: minimal
on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/deadshot465/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL1 $env:WEBHOOK_URL2
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/deadshot465/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL1 $env:WEBHOOK_URL2